M48
; DRILL file {KiCad 9.0.6} date 2026-05-03T18:52:31-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-03T18:52:31-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X103.6Y-75.9
X103.8Y-185.1
X196.2Y-76.0
X196.3Y-184.9
M30
